### ISSUE TITLE
Propuesta de colores para Logo

### ISSUE THREAD

**Issue by marioalverto** [rubixware/blist-frontend#1]
Proponer cuando menos 3 colores para logo y una idea en base a imagen existente.

**Comment by andreeasalinaas** [comment]
![captura de pantalla de 2015-10-10 18 17 45](https://cloud.githubusercontent.com/assets/15068856/10413868/c27c17aa-6f80-11e5-8f18-79fa879586b4.png)
![captura de pantalla de 2015-10-10 18 13 35](https://cloud.githubusercontent.com/assets/15068856/10413869/c27c8eec-6f80-11e5-9546-c7758d3eeecc.png)
