### ISSUE TITLE
Modulo/Vista de lista de empresas

### ISSUE THREAD

**Issue by marioalverto** [rubixware/blist-frontend#10]
Vista de pre-view de las empresas a mostrar, la base debe ser el Logo, nombre de la empresa, categoría y tags de la empresa.

**Comment by andreeasalinaas** [comment]
![vista lista](https://cloud.githubusercontent.com/assets/15068856/10414521/e8f653be-6f9e-11e5-8cff-f15ce45e2a5f.png)
