### ISSUE TITLE
Modulo/Vista del mapa 

### ISSUE THREAD

**Issue by marioalverto** [rubixware/blist-frontend#11]
Idea central del mapa.

**Comment by andreeasalinaas** [comment]
![map1](https://cloud.githubusercontent.com/assets/15068856/10414161/dca28204-6f8a-11e5-92c4-1f9522b79a80.png)
![map2](https://cloud.githubusercontent.com/assets/15068856/10414162/dcaebf24-6f8a-11e5-947a-9dcfcbc719b9.png)

![1444543105_03 office](https://cloud.githubusercontent.com/assets/15068856/10414172/4d3e9656-6f8b-11e5-96ce-d433e198bfcf.png)
![1444543063_02 shop](https://cloud.githubusercontent.com/assets/15068856/10414173/4d3f5fe6-6f8b-11e5-8255-851686e133af.png)
![1444543043_30 user](https://cloud.githubusercontent.com/assets/15068856/10414171/4d3e80a8-6f8b-11e5-8ef4-5455f371804f.png)

![1444572243_manager](https://cloud.githubusercontent.com/assets/15068856/10416116/801ad642-6fcd-11e5-93ee-fc4f817a50e3.png)
![1444572331_department](https://cloud.githubusercontent.com/assets/15068856/10416115/801aabe0-6fcd-11e5-9d73-6d3afed22322.png)
![1444572338_shop](https://cloud.githubusercontent.com/assets/15068856/10416114/8018c6fe-6fcd-11e5-9152-52f6d256d11d.png)

**Comment by andreeasalinaas** [comment]
![1444543171_department](https://cloud.githubusercontent.com/assets/15068856/10414165/3bca6f12-6f8b-11e5-80fb-3bb89afa6cd9.png)
![1444543166_shop](https://cloud.githubusercontent.com/assets/15068856/10414164/3bc92af8-6f8b-11e5-9ea9-5863b775982c.png)
![1444543141_manager](https://cloud.githubusercontent.com/assets/15068856/10414166/3bcdba82-6f8b-11e5-96bd-5d683bcb4961.png)
